### ISSUE TITLE
ask for help about instpred of facebook

### ISSUE THREAD

**Issue by birdflyto** [Xiaoyin96/Equilibrium_Generators#1]
hi 小姐姐@Xiaoyin96  ， 非常抱歉在这里向你请教一个不是这个repo的问题，
![image](https://user-images.githubusercontent.com/44084928/93544995-f12c2e00-f991-11ea-9203-af7c9ab04366.png)

不知道你还记得之前跑过的facebook/instpred的模型，我看issue，你应该是跑通了。我自己debug了，加载procamputed features 时，一直报错IOError: Failed to interpret file u'precomputed/P5_fr3_features/train__fpn_res5_2_sum__nSeq5__fr3__features.npy' as a pickle
利用mask-rcnn的模型去生成precomputed features 可能是加载位置不对，生成precomputed 的features也失败了。非常希望小姐姐你帮我看看哪里有问题吗？非常感谢。如果能回1521361730@qq.com，就再感谢不过了

**Comment by Xiaoyin96** [comment]
Hello, 因为是一年多前跑的代码，代码本身在学校的server上，我现在也没法复现了。 我想到几个可能的原因你看看有没有帮助：
1. numpy 版本 （可以在本地试试能不能load）
2. precomputed feature是很大的，确保你完整下载下来了（Git LFS）
3. 尝试直接用file.readline()读取后再用np.save保存
4. 你是在ubuntu/win/mac上跑的？有可能是系统问题，建议使用ubuntu.

**Comment by birdflyto** [comment]
谢谢小姐姐，
我自己单独把pre computed features的npy和预训练的权重下载下来了，正在Centos7服务器上，试这个numpy和pickel load.&nbsp;



---Original---
